### ISSUE TITLE
Link Externo para Blog

### ISSUE THREAD

**Issue by pedrohenriquecunha** [scadete/cidadaofiscal#1]
Mostrar o conteúdo do blog do wordpress através de link externo.

**Comment by scadete** [comment]
O link externo foi adicionado diretamente no comportamento do wordpress. Assim é possível manter a listagem dos posts ainda no portal, mas a leitura dedicada em uma nova página.

Esta ainda não é a funcionalidade final esperada, porque espero que façamos uma integração com o wordpress via API, mas é bem próximo do que teremos e acredito que melhora sensivelmente a experiência movel.
